set(CMAKE_TARGET_OS macosx)
set(CMAKE_TARGET_CPU_ARCH intel)
set(CMAKE_TARGET_CPU_ARCH_FAMILY x86_64)
set(CMAKE_SHARED_LIBS_ALLOWED_ON_TARGET TRUE)
set(CMAKE_STATIC_LIBS_ALLOWED_ON_TARGET TRUE)
set(CMAKE_COMPILER_FAMILY clang)
set(CMAKE_ASM_FLAGS "-stdlib=libc++ -fPIC")
set(CMAKE_C_FLAGS "-O2 -stdlib=libc++ -fPIC -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function")
set(CMAKE_CXX_FLAGS "-O2 -stdlib=libc++ -fPIC -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function")
set(CMAKE_SHARED_LINKER_FLAGS "-stdlib=libc++ -fPIC")
set(CMAKE_MODULE_LINKER_FLAGS "-stdlib=libc++ -fPIC")
set(CMAKE_EXE_LINKER_FLAGS "-stdlib=libc++ -fPIC")
set(CMAKE_OSX_ARCHITECTURES "x86_64")
set(CMAKE_OSX_DEPLOYMENT_TARGET "14.2")

